name: sync-fork
run-name: "Syncs the fork and restructures it, every hour."
on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository code (necessary - otherwise the workspace is empty)
        uses: actions/checkout@v4
        with:
          # Fine-grained PAT with contents:write and workflows:write
          # scopes
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: "sync with colonial-collections/research-guides-dev. --force overrides everything (current solution from here: https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github)!"
        run: |
          git config user.email "valevogelmann@gmail.com"
          git config user.name "valevo"
          git reset --hard
          git remote add upstream https://github.com/colonial-heritage/research-guides-dev.git
          git fetch upstream

          # EXPERIMENTAL
          git merge -s theirs upstream/main
          # EXPERIMENTAL
          
          # git checkout upstream/main
          # git merge -s ours --allow-unrelated-histories origin/main # should this be "theirs"???
          ## git branch mycrazybranch # this is not needed? (seems like this branch isn't used at all)
          # git checkout origin/main
          ## git merge upstream/main
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/EXPORTS/WEBSITE/*
      - name: "clone research-aids/research-aids.github.io-code and add contents to research-aids.github.io"
        run: |
          git clone https://github.com/research-aids/research-aids.github.io-code.git
          ls
          ls $WORK_DIR
          ls research-aids.github.io-code/
          cp --force $WORK_DIR/research-aids.github.io-code/sync-fork.yml $WORK_DIR/.github/workflows
          
          cp -r --force $WORK_DIR/research-aids.github.io-code/docs $WORK_DIR
          cp --force $WORK_DIR/docs/pages.yml $WORK_DIR/.github/workflows
          # cp --force $WORK_DIR/docs/ci.yml $WORK_DIR/.github/workflows
          
          cp --force $WORK_DIR/research-aids.github.io-code/clean_up.py $WORK_DIR
          python $WORK_DIR/clean_up.py

          rm -rf $WORK_DIR/research-aids.github.io-code
        env:
          WORK_DIR: ${{ github.workspace }}
      - name: pushing generated files back to repo 
        run: |
          if git diff --quiet --exit-code; then
            echo "NOTHING TO COMMIT! WEIRD?"
          else
            git config user.email "valevogelmann@gmail.com"
            git config user.name "valevo"
            git add .
            git commit -m "automated commit by GitHub Action defined in https://github.com/research-aids/research-aids.github.io-code/sync-fork.yml"
            git push origin HEAD:refs/heads/main --force
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
