name: sync-fork
run-name: "Syncs the fork and restructures it, every 15 minutes. 3 hours."
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "sync with colonial-collections/research-guides-dev. --force overrides everything!"
        run: gh repo sync --force $REPOSITORY -b $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
      - name: "clone research-aids/research-aids.github.io-code and add contents to research-aids.github.io"
        run: |
          git clone https://github.com/research-aids/research-aids.github.io-code.git $WORK_DIR
          cp --force $WORK_DIR/research-aids.github.io-code/sync-fork.yml $WORK_DIR/.github/workflows
          
          cp -r --force $WORK_DIR/research-aids.github.io-code/docs $WORK_DIR
          cp --force $WORK_DIR/docs/pages.yml $WORK_DIR/.github/workflows
          cp --force $WORK_DIR/docs/ci.yml $WORK_DIR/.github/workflows
          
          cp --force $WORK_DIR/research-aids.github.io-code/clean_up.py $WORK_DIR
          python $WORK_DIR/clean_up.py
        env:
          WORK_DIR: ${{ github.workspace }}/research-aids.github.io
      - name: pushing generated files back to repo 
        run: |
          if git diff --exit-code; then
            echo "NOTHING TO COMMIT!!!"
          else
            git config user.email "valevogelmann@gmail.com"
            git config user.name "valevo"
            git add .
            git commit -m "automated commit by GitHub Action defined in scripts/yaml_to_json.yml"
            git push
          fi
