name: sync-fork
run-name: "Syncs the fork and restructures it, every 3 hours."
on:
  schedule:
    - cron: '* */3 * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "sync with colonial-collections/research-guides-dev. --force overrides everything!"
        run: gh repo sync --force $REPOSITORY -b $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
      - name: "clone research-aids/research-aids.github.io-code and add contents to research-aids.github.io"
        run: |
          git clone https://github.com/research-aids/research-aids.github.io-code.git
          cp --force research-aids.github.io-code/
             
