title: Research Aids
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://research-aids.github.io

aux_links:
  Research Aids repository: https://github.com/colonial-heritage/research-guides-dev/

aux_links_new_tab: true
